baseurl = 'https://antoninfaure.ch'
DefaultContentLanguage = "en"
theme = 'beautifulhugo'
googleAnalytics='G-DNX97H63H6'
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  homeTitle = "Antonin Faure"
  mainSections = ["post", "work", "project"]
  socialShare = true
  hideAuthor = true
  custom_css = ["custom.css"]
[markup]
  [markup.highlight]
    noclasses = false

[languages]
  [languages.en]
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        url = ""
        weight = 1
        name = "Home"
      [[languages.en.menu.main]]
        url = "page/about"
        weight = 2
        name = "About"
      [[languages.en.menu.main]]
        url = "post"
        weight = 3
        name = "Posts"
      [[languages.en.menu.main]]
        url = "project"
        weight = 4
        name = "Projects"
      [[languages.en.menu.main]]
        url = "work"
        weight = 5
        name = "Work"

  [languages.fr]
    contentDir = "content/fr"
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        url = ""
        weight = 1
        name = "Accueil"
      [[languages.fr.menu.main]]
        url = "page/about"
        weight = 2
        name = "A propos"
      [[languages.fr.menu.main]]
        url = "post"
        weight = 3
        name = "Posts"
      [[languages.fr.menu.main]]
        url = "project"
        weight = 4
        name = "Projets"
      [[languages.fr.menu.main]]
        url = "work"
        weight = 5
        name = "RÃ©alisations"
    
[Author]
  name = "Antonin Faure"
  website = "antoninfaure.ch"
  email = "antonin.faure6@gmail.com"
  github = "antoninfaure"
  gitlab = "antonin_faure"
  linkedin = "antoninfaure"
  telegram = "antonin_faure"
  medium = "antonin.faure"
  kaggle = "antoninfaure"

[module]
  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/images"